# Add paths to FRANKIE_FILE_TESTS
list(APPEND FRANKIE_FILE_TESTS ${CMAKE_CURRENT_LIST_DIR}/booleans.frankie)
list(APPEND FRANKIE_FILE_TESTS ${CMAKE_CURRENT_LIST_DIR}/numbers.frankie)
list(APPEND FRANKIE_FILE_TESTS ${CMAKE_CURRENT_LIST_DIR}/strings.frankie)
